// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPIBiblioteca;

#nullable disable

namespace WebAPIBiblioteca.Migrations
{
    [DbContext(typeof(ApplicatonDbContext))]
    partial class ApplicatonDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebAPIBiblioteca.Entidades.Clases.Editorial", b =>
                {
                    b.Property<int>("EditorialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EditorialId"), 1L, 1);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EditorialId");

                    b.ToTable("Editoriales");

                    b.HasData(
                        new
                        {
                            EditorialId = 1,
                            Nombre = "Planeta"
                        },
                        new
                        {
                            EditorialId = 2,
                            Nombre = "Aguilar"
                        });
                });

            modelBuilder.Entity("WebAPIBiblioteca.Entidades.Clases.Libro", b =>
                {
                    b.Property<int>("LibroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LibroId"), 1L, 1);

                    b.Property<int?>("EditorialId")
                        .HasColumnType("int");

                    b.Property<int>("EditorialIdentificador")
                        .HasColumnType("int");

                    b.Property<int>("Páginas")
                        .HasPrecision(1, 1000)
                        .HasColumnType("int");

                    b.Property<string>("Título")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("LibroId");

                    b.HasIndex("EditorialId");

                    b.ToTable("Libros");

                    b.HasData(
                        new
                        {
                            LibroId = 1,
                            EditorialIdentificador = 1,
                            Páginas = 300,
                            Título = "El Quijote"
                        },
                        new
                        {
                            LibroId = 2,
                            EditorialIdentificador = 1,
                            Páginas = 350,
                            Título = "Cien años de soledad"
                        },
                        new
                        {
                            LibroId = 3,
                            EditorialIdentificador = 2,
                            Páginas = 500,
                            Título = "El amor en los tiempos del cólera"
                        },
                        new
                        {
                            LibroId = 4,
                            EditorialIdentificador = 1,
                            Páginas = 300,
                            Título = "Divina comedia"
                        },
                        new
                        {
                            LibroId = 5,
                            EditorialIdentificador = 1,
                            Páginas = 350,
                            Título = "El extranjero"
                        },
                        new
                        {
                            LibroId = 6,
                            EditorialIdentificador = 2,
                            Páginas = 1000,
                            Título = "Crimen y castigo"
                        },
                        new
                        {
                            LibroId = 7,
                            EditorialIdentificador = 1,
                            Páginas = 1500,
                            Título = "El hombre invisible"
                        },
                        new
                        {
                            LibroId = 8,
                            EditorialIdentificador = 1,
                            Páginas = 850,
                            Título = "Almas muertas"
                        },
                        new
                        {
                            LibroId = 9,
                            EditorialIdentificador = 2,
                            Páginas = 900,
                            Título = "El castillo"
                        },
                        new
                        {
                            LibroId = 10,
                            EditorialIdentificador = 2,
                            Páginas = 800,
                            Título = "Pippi Calzaslargas"
                        });
                });

            modelBuilder.Entity("WebAPIBiblioteca.Entidades.Clases.Libro", b =>
                {
                    b.HasOne("WebAPIBiblioteca.Entidades.Clases.Editorial", "Editorial")
                        .WithMany()
                        .HasForeignKey("EditorialId");

                    b.Navigation("Editorial");
                });
#pragma warning restore 612, 618
        }
    }
}
